;; The Louis's definition calls sqrt-stream recursively but each objects generated by sqrt-stream are not shared, so the redundant computation occurs.

;; The original one is more efficient because the each element in the stream is optimized with memo-proc so the computation for each element occurs only once, but without memo-proc, the computation occurs everytime it is called.









