(define (pascals-triangle row col)
  (cond ((or (= row 1) (= col 1)) 1)
	((= row col) 1)
	(else (+ (pascals-triangle (- row 1) (- col 1))
		 (pascals-triangle (- row 1) col)))))


(pascals-triangle 1 1)
(pascals-triangle 1 2)
(pascals-triangle 2 2)
(pascals-triangle 3 1)
(pascals-triangle 3 2)
(pascals-triangle 3 3)
(pascals-triangle 4 1)
(pascals-triangle 4 2)
(pascals-triangle 4 3)
(pascals-triangle 4 4)
(pascals-triangle 5 1)
(pascals-triangle 5 2)
(pascals-triangle 5 3)
(pascals-triangle 5 4)
(pascals-triangle 5 5)
