(define (fast-expt b n)
  (define (even? n)
    (= (remainder n 2) 0))
  (define (iter a b n)
    (cond ((= n 0) a)
	  ((even? n) (iter a (* b b) (/ n 2)))
	  (else (iter (* a b) b (- n 1)))))
  (iter 1 b n))
(fast-expt 2 3)
(fast-expt 2 4)
(fast-expt 3 2)
(fast-expt 5 3)
(fast-expt 3 100000)

