(and (job ?x (computer programmer))
     (supervisor ?x ?y))

(and (supervisor ?x ?y)
     (job ?x (computer programmer)))
;; If supervisors is less than programmer,
;; the first is better than the second because
;; the number of intermediate frames is less.

;; The aim of logical programming is to provide the programmers
;; the technique of decomposing 'what' is to be computed and 'how' that should be computed.

;; 'Rule' holds the 'way' to compute the problem procedurally in body, at the same time,
;; this can be regarded as the 'statement(what)' of methematical logic (inference).

;;;; Inifinite loops

(assert! (married Minnie Mickey))

(married Mickey ?who) ;; no match

(assert! (rule (married ?x ?y) (married ?y ?x)))

(married Mickey ?who) ;; Infinite loop

;;;; Problems with not

(and (supervisor ?x ?y)
     (not (job ?x (computer programmer))))

(and (not (job ?x (computer programmer)))
     (supervisor ?x ?y))
;; Those above dont result in same result.

;; At the first one,
;; The first part of the expression matches to (supervisor ?x ?y)

;; (supervisor (Hacker Alyssa P) (Bitdiddle Ben))
;; (supervisor (Fect Cy D) (Bitdiddle Ben))
;; (supervisor (Tweakit Lem E) (Bitdiddle Ben))
;; (supervisor (Reasoner Louis) (Hacker Alyssa P))
;; (supervisor (Bitdiddle Ben) (Warbucks Oliver))
;; (supervisor (Scrooge Eben) (Warbucks Oliver))
;; (supervisor (Cratchet Robert) (Scrooge Eben))
;; (supervisor (Aull DeWitt) (Warbucks Oliver))

;; then the stream of frames generated by the first part is as follows

;; (?x (Hacker Alyssa P))
;; (?x (Fect Cy D))
;; (?x (Tweakit Lem E))
;; (?x (Reasoner Louis))
;; (?x (Bitdiddle Ben))
;; (?x (Scrooge Eben))
;; (?x (Cratchet Robert))
;; (?x (Aull DeWitt))

;; which are passed to the second part of expression (not (job ?x (computer programmer)))

;; (not (job (Hacker Alyssa P) (computer programmer))) ;; false: Hacker is (computer programmer) in DB
;; (not (job (Fect Cy D) (computer programmer))) ;; false: Fect is (computer programmer) in DB
;; (not (job (Tweakit Lem E) (computer programmer))) ;; true: Tweakit is (computer technician)
;; (not (job (Reasoner Louis) (computer programmer))) ;; true: Reasoner is (computer programmer trainee) in DB
;; (not (job (Bitdiddle Ben) (computer programmer))) ;; true: Bitdiddle is (computer wizard) in DB
;; (not (job (Scrooge Eben) (computer programmer))) ;; true: Scrooge is (accounting chief accountant)
;; (not (job (Cratchet Robert) (computer programmer))) ;; true: Cratchet Robert is (accounting scriverner)
;; (not (job (Aull DeWitt) (computer programmer))) ;; true: Aull is (administration secretary)

;; then all expressions generate the stream of the frame as follows,

;; (?x (Tweakit Lem E))
;; (?x (Reasoner Louis))
;; (?x (Bitdiddle Ben))
;; (?x (Scrooge Eben))
;; (?x (Cratchet Robert))
;; (?x (Aull DeWitt))

;; 'not' filters the "incomming frames (not database)" which don't match (job ?x (computer ...))
;; At the second one, the incommint frames initially are empty then
;; (not (job ?x (computer programmer)) results in empty so the entire expression
;; of the second results in empty frames.
;; This occurs because ?x is unbound.

;; In the first part of expression (job ?x (computer programmer)) matches to the entries of database


;; (job (Hacker Alyssa P) (computer programmer))
;; (job (Fect Cy D) (computer programmer))

;; On the other hand, the incoming frame is
;; (<empty>)

;; Anytime there are the matched entries, then 'not' filter out the incomming empty frame
;; then results in the empty stream of frames.
;; The second part is evaluated by the empty stream then the entire expression results in the empty stream of frames.
